FROM alpine

LABEL author="bima afrizal"
LABEL company="Entahlah" website="https://bimaafrizal.github.io/"

RUN mkdir hello
RUN echo "hello world" > hello/hello.txt
RUN cat "hello/hello.txt"

CMD cat "hello/hello.txt"